platform :ios, "9.0"
use_frameworks!
inhibit_all_warnings!

install! 'cocoapods', :deterministic_uuids => false

target 'z02sckhd_6wQgx_User_Example' do
  pod 'z02sckhd_6wQgx_User', :path => '../'

  target 'z02sckhd_6wQgx_User_Tests' do
    inherit! :search_paths
    
    
  end
end
